# ==================================
# Namespace (si non existant)
# ==================================
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

# ==================================
# Secret (pour les variables sensibles)
# ==================================
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  MONGO_URI: "mongodb://louaymoncef:isetch@10.9.21.20:30007/product-db"
  SECRET_KEY: "devops2024!@#"

---

# ==================================
# Deployment 🚀
# ==================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: mohamedlouay/product-service-flask:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY

---

# ==================================
# Service (NodePort) 🌐
# ==================================
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30051
